# Generated by Django 5.0.4 on 2024-06-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_usn',
            field=models.CharField(max_length=122, unique=True),
        ),
    ]
